use_default_settings: true

general:
  instance_name: PriceComparerWeb SearXNG

search:
  formats:
    - html
    - json

server:
  bind_address: 0.0.0.0
  port: 8080
  secret_key: price-comparer-web-local-development-secret
